### ISSUE TITLE
HassOs and Bluez

### ISSUE THREAD

**Issue by bubez81** [tikismoke/home-assistant-nespressoble#1]
Any idea on how to use this integration on HassOs?
Ps...well done!!! I’m wating this integration from years!!

**Comment by tikismoke** [comment]
Hi,

Sorry do not know how hassOS works. I'm going to have to look out it a little more...

What's part is not working for you for the moment?
Can we talk about it on discord in few minutes or in the evening?

**Comment by bubez81** [comment]
Sure! I’m not in a hurry! The problem is that you can’t install bluez on HassoOs

**Comment by tikismoke** [comment]
Solved at least with an external USB dongle.

**Comment by bubez81** [comment]
yes, solved! on hassos you have to use the command bluetoothctl and scan on (with the add-on SSH & Web Terminal) (my setup is a Mac mini with vmware, hassos virtualized and a usb bluetooth dongle).
