### ISSUE TITLE
ESpHome Proxy Bluetooth

### ISSUE THREAD

**Issue by leovj** [tikismoke/home-assistant-nespressoble#12]
Hi tikismoke, if I use BLE Client for Esphome, do you think the integration will work? Where could I specify to use this device?

Thanks

**Comment by tikismoke** [comment]
Sorry have no idea at all how to do that 😔

**Comment by leovj** [comment]
Using ESPHome Bluetooth Proxy to connect to the machine, is there a way to change where the integration goes to read the bluetooth data? No on the USB dongle, but on ESP32..

**Comment by tikismoke** [comment]
Certainly but I do not know where neither how to do that.
As already said I do no more work on this as I own no more a compatible lachine

**Comment by rucanunes** [comment]
Will this work on a Nespresso VERTUO Next?

**Comment by tikismoke** [comment]
> 

If it has Bluetooth connection it should. The communication with the machine is the same on all of them.

**Comment by rucanunes** [comment]
I still don't know how to get this "resource: 8287ee82593d3c4e".
My native language it's not English. Is there a step by step tutorial on how to get that number?

Thank you!

**Comment by tikismoke** [comment]
> I still don't know how to get this "resource: 8287ee82593d3c4e". My native language it's not English. Is there a step by step tutorial on how to get that number?
> 
> Thank you!

https://gist.github.com/farminf/94f681eaca2760212f457ac59da99f23

https://github.com/tritter/homebridge-brewer#token

https://github.com/petergullberg/brewbutton#retrieve-auth-key

👍

**Comment by rucanunes** [comment]
I installed and run the Nexpresso app on a tablet.
I could see all that the machine was doing in the app with "Enable Bluetooth HCI snoop log" ON.
After I brew a coffe I stopped "Enable Bluetooth HCI snoop log".
I can't find the "btsnoop_hci.log" file anywhere!! Damn!!

What am I doing wrong? I used it with and without an SD card and I was on Developer Mode".

**Comment by rucanunes** [comment]
I just realized why my machine doesn't record BT. 
It's connected to the wifi network.
Is there a way to get the token via wifi?

**Comment by catduckgnaf** [comment]
@rucanunes did you ever figure it out? I think if I try resetting it, or turning off the wifi network might force it to show the code over BT?

**Comment by catduckgnaf** [comment]
hexdump -v -e ‘/1 "%02X "’ /mnt/user/media/btsnoop_hci.log | grep -o '0B 00 04 00 12 30 00 <… … … … … … .

. …>’

**Comment by tikismoke** [comment]
@leovj @rucanunes @catduckgnaf @soundch3z 

Try this repo it's also using ble ha proxy:

https://github.com/bulldog5046/ha_nespresso_ingetration
