### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by flexdev91** [tikismoke/home-assistant-nespressoble#14]
Hi,
Very great work !
I just installed but I get an error "Connection timeout after 5 seconds".
An idea ?
Thx !

**Comment by tikismoke** [comment]
Most if the time a distance issue.
That's why I made a matt script to reduce this one.
Unfortunately I do no more own one.

**Comment by saya6k** [comment]
I am encountering connectivity issues with my BLE device when its signal strength ranges from -35 to -60 dBm. I tried ESPhome Bluetooth Proxy and BT dongle, neither worked... The device is located in close proximity to a Nespresso Expert machine.
B

**Comment by tikismoke** [comment]
> I am encountering connectivity issues with my BLE device when its signal strength ranges from -35 to -60 dBm. I tried ESPhome Bluetooth Proxy and BT dongle, neither worked... The device is located in close proximity to a Nespresso Expert machine.
> B

Try this repo it support blé proxy from Ha:

https://github.com/bulldog5046/ha_nespresso_ingetration
