### ISSUE TITLE
Auth code to hex

### ISSUE THREAD

**Issue by SilvanLaroo** [tikismoke/home-assistant-nespressoble#15]
Hi Tikismoke,

Thanks for your great work. I'm trying to make the mqtt script work, there's an auth code needed in hex format. How do I go from my auth key (I already retrieved it) to the hex array format?

Regards,
Silvan

**Comment by tikismoke** [comment]
Just sebarate each byte and add 0x before.
In this example:
0x82, 0x87,0xee,0x82,0x59,0x3d,0x3c,0x4e
The auth code is 8287ee82593d3c4e

**Comment by tikismoke** [comment]
Hope it helps.

**Comment by SilvanLaroo** [comment]
Ah great, thanks!
