### ISSUE TITLE
Looking for an advice

### ISSUE THREAD

**Issue by dredkin** [tikismoke/home-assistant-nespressoble#7]
Hello, looking for an advice here!
I have a Nespresso Expert&Milk machine with Bluetooth.
In order to use your code I have to get an authorization token. The problem is that official Nespresso application is banned in Russia, and AFAICS to get that token you MUST run an official app at least once.
Earlier I managed to control my machine with an official app downloaded from some third-party server, but now this old version shows "Upgrade is needed" dialog and the new official version downloaded from apkpure just refuses to install: I guess  because of my country too.
SO, any advice appreciated: How can I run this version or maybe get auth token without an official app?
I've installed nrf Connect but cant see anything like auth token in the logs

**Comment by tikismoke** [comment]
Sorry show this only now.
indeed nrfconnect won't let you get the auth code, you really need the official apps.

Why not try a free external vpn to get the apps?


Just let me know, why do a coffe apps is banned in russia? WTF is the risk?

**Comment by dredkin** [comment]
Thank for the answer!
Yes Nesrpesso app is banned (Stupid Russian Law forbids to send "personal data" abroad).
But I've already managed to install it  registering a new Google account from Europe (over VPN)..

For everybody who wants to do it: 
1.  Establish a VPN to any European Country
2.  Create new gmail account 
3.  Check  that it  is registered to a European Country,
4.  Add this account to your Android phone.
5. Install the app.

**Comment by tikismoke** [comment]
> Thank for the answer!
> Yes Nesrpesso app is banned (Stupid Russian Law forbids to send "personal data" abroad).
> But I've already managed to install it registering a new Google account from Europe (over VPN)..


Ok so I think you have everything to do it now 👍
