### ISSUE TITLE
Verifying configuration after installation: Platform error sensor.nespresso - Integration 'nespresso' not found.

### ISSUE THREAD

**Issue by janfajessen** [tikismoke/home-assistant-nespressoble#9]
After install with hacs, nespresso file in custom components.  And the sensor configuration good...
Platform error sensor.nespresso - Integration 'nespresso' not found.
No way to work... impossible

**Comment by tikismoke** [comment]
Sorry you might have a mistake somewhere.

Watch out your config and has install dir.

**Comment by soundch3z** [comment]
I think there's a new syntax for Binary sensors, in sensor.py it should import  "BinarySensorEntity" instead of "BinarySensorDevice", I made this change in my repo and now it works again. already sent a pull request @tikismoke , hope it helps.

**Comment by tikismoke** [comment]
Solve trough #10
